### ISSUE TITLE
Sort the environments returned by `/api/v1/environment/`

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/conda-store#129]
Currently, paginated results are returned from a GET request targeting the `/api/v1/environment/` endpoint. Unlike the `/api/v1/package/` endpoint, the environments returned in the response are not sorted. To make the endpoints behave the same, it would be useful to have the environments sorted in the response.

**Comment by costrouc** [comment]
I'd suggest that we add two optional query parameters to paginated queries. `sort_by` and `order`. `sort_by` key will have a set of keys that a result can be sorted over. `order` will take `asc` or `dec` as values. Thoughts?

**Comment by peytondmurray** [comment]
Sounds great to me. `/api/v1/build/` could be sorted over (namespace, environment name, build number), as well.

**Comment by pierrotsmnrd** [comment]
After discussing with @costrouc we agreed on having `sort_by` and `oder` as parameters.

The `sort_by` parameter can be an array parameter, to sort on multiple fields. 
Example : environment will be sortable by namespace, or name, or both in the given order.  
```
?sort_by=namespace                 -> sort by namespace
?sort_by=name                      -> sort by name
?sort_by=namespace&sort_by=name    -> sort by namespace and name
?sort_by=name&sort_by=namespace    -> sort by name and namespace
```

The `order` parameter is either `asc` (default)  or `desc`.

Work is in progress in [the fix_129 branch](https://github.com/Quansight/conda-store/tree/fix_129)
