### ISSUE TITLE
build starting again since past timeout

### ISSUE THREAD

**Issue by brl0** [Quansight/conda-store#13]
Conda-store ran out of space on our qhub deployment, so I opened a shell through k9s to remove old copies of environments to free up space.  Once complete, and the timeout elapsed, conda-store successfully built the updated environment.
However, now every 10s there is a message in the logs stating `build starting again since past timeout`.  This seems to be a bug in conda-store.  I suspect that for now the most appropriate course of action is to kill the pod so it can restart, but this will affect on-going processing so I will need to wait for the cluster to not be in use.  

@kcpevey, @costrouc

**Comment by costrouc** [comment]
Related to issue #7

**Comment by costrouc** [comment]
This will be solved by #22 once implemented.

**Comment by costrouc** [comment]
Closing since resolved in upcoming 0.3.0 release.
