### ISSUE TITLE
Feature : Create environment

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#132]
**Goal :** 
- Port the following feature of Gator using Conda Store : **Create environment**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store 

**Other notes :** 
With a mamba/conda backend, the new env is created with a number of default packages. I don't think Conda Store provides default packages.

**Comment by costrouc** [comment]
From @pierrotsmnrd 

> can Conda Store build R environments?

I don't see any reason why not. As long as it can normally be built via conda it should work.

**Comment by pierrotsmnrd** [comment]
Comments from @dharhas  :  To build R environments, we just need to add the R channels.

**Comment by dharhas** [comment]
https://docs.anaconda.com/anaconda/packages/r-language-pkg-docs/

**Comment by peytondmurray** [comment]
We need an endpoint to create namespaces: blocked by https://github.com/Quansight/conda-store/issues/177.

**Comment by pierrotsmnrd** [comment]
Works now, waiting for a PR.

**Comment by peytondmurray** [comment]
Currently blocked because Frederic cannot test (but he has approved the code: https://github.com/mamba-org/gator/pull/162). I would appreciate it if anyone who has a chance can test and post in the PR above.

**Comment by peytondmurray** [comment]
Merged: https://github.com/mamba-org/gator/pull/162
