### ISSUE TITLE
Feature : List installable packages of a given env

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#133]
**Goal :** 
- Port the following feature of Gator using Conda Store : **List installable packages of a given env**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store 

**Other notes :** 
Show the packages with their version and channel

**Comment by peytondmurray** [comment]
Blocked by https://github.com/Quansight/conda-store/issues/151.

**Comment by pierrotsmnrd** [comment]
Issue #151 has been solved now, so this issue is unblocked :)

**Comment by peytondmurray** [comment]
Merged: https://github.com/mamba-org/gator/pull/155
