### ISSUE TITLE
Feature : install packages in a given env

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#135]
**Goal :** 
- Port the following feature of Gator using Conda Store : **install packages in a given env**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store

**Comment by pierrotsmnrd** [comment]
After discussing with Chris during today's meeting, my previous comment is invalid : only the second step is needed.

➞ update the env to use the new build (`PUT /api/v1/environment/<namespace>/<name>/ `)

**Comment by peytondmurray** [comment]
Blocked by https://github.com/Quansight/conda-store/issues/202.

**Comment by pierrotsmnrd** [comment]
The bug in #202 breaks the functionality for any namespace that is not default.

**Comment by pierrotsmnrd** [comment]
PR in progress : https://github.com/mamba-org/gator/pull/169

**Comment by peytondmurray** [comment]
Small update: I pushed changes which fix the issue that Frederic reported. The fix I implemented affects more than just package installation - it improves behavior of the package list for _any_ package modifications. Hopefully it can get merged soon!

**Comment by kcpevey** [comment]
Closing as this is no longer valid.
