### ISSUE TITLE
Feature : List updatable packages of a given env

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#137]
**Goal :** 
- Port the following feature of Gator using Conda Store : **List updatable packages of a given env**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store 

**Other notes :** 
Show the packages with their version and channel

**Comment by pierrotsmnrd** [comment]
Due to how the frontend works, it may already be functional. needs to be verified.

**Comment by kcpevey** [comment]
Closing as this is no longer valid.
