### ISSUE TITLE
Feature : Filter a list of packages with the search field

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#138]
**Goal :** 
- Port the following feature of Gator using Conda Store : **Filter a list of packages with the search field**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store

**Comment by pierrotsmnrd** [comment]
PR (wip) : https://github.com/mamba-org/gator/pull/175

**Comment by kcpevey** [comment]
This is currently available.
