### ISSUE TITLE
jupyterhub authentication integration

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#14]
Closing in favor of #62 . Duplicate

**Comment by echarles** [comment]
@costrouc A proposal for Kernel Environment Provisioning  (KEP) has just been posted on https://github.com/jupyter/jupyter_client/issues/608

In terms of jhub auth, I am working atm on adding auth to the standalone jupyter server.  I have something working with OAuth Github (`jupyter server --ServerApp.login_handler_class=jupyter_server.auth.login_github.LoginGithubHandler`) and looking in the middle term reusing the jhub authenticator libraries (if possible). Happy to read and discover more on your plan in terms of jhub auth integration.
