### ISSUE TITLE
Feature : Remove environment

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#141]
**Goal :** 
- Port the following feature of Gator using Conda Store : **Remove environment**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store

**Comment by jess-x** [comment]
CORS policy limitation occurs in the development of this feature, https://github.com/Quansight/conda-store/issues/201 for reference

**Comment by jess-x** [comment]
@peytondmurray @gabalafou I found that after implemented the `remove()` with fetch DELETE at the "correct" endpoints. I would still need to click the refresh button to see the changes.
