### ISSUE TITLE
Feature : Clone environment

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#142]
**Goal :** 
- Port the following feature of Gator using Conda Store : **Clone environment**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store

**Comment by jess-x** [comment]
@peytondmurray @gabalafou 
In the developing of this feature, some note I took:
- Is there an API end points to clone environments across different namespaces?
- when I tried to clone under the some namespace, an error I run into when just trying to using the same .yml for a new build
![Screen Shot 2021-11-30 at 8 28 16 AM](https://user-images.githubusercontent.com/22648112/144087322-afba4758-d031-42e7-a87f-eba145dce428.png)

**Comment by anirrudh** [comment]
@pierrotsmnrd @peytondmurray I don't see a branch open for this issue, so I'm going to go ahead and open a new branch.
