### ISSUE TITLE
Feature : Export environment

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#143]
**Goal :** 
- Port the following feature of Gator using Conda Store : **Export environment**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store

**Comment by pierrotsmnrd** [comment]
Work in progress, @peytondmurray needs some advices from @jess-x  and @gabalafou .

**Comment by peytondmurray** [comment]
This is now working well, will make a PR for mamba-org/gator.

**Comment by peytondmurray** [comment]
Blocked by https://github.com/Quansight/conda-store/pull/204

**Comment by pierrotsmnrd** [comment]
PR opened : https://github.com/mamba-org/gator/pull/165

**Comment by peytondmurray** [comment]
Merged: https://github.com/mamba-org/gator/pull/165
