### ISSUE TITLE
Feature : Import environment

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#144]
**Goal :** 
- Port the following feature of Gator using Conda Store : **Import environment**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store

**Comment by peytondmurray** [comment]
Blocked by #132 (PR: https://github.com/mamba-org/gator/pull/162).

**Comment by peytondmurray** [comment]
Merged: https://github.com/mamba-org/gator/pull/163
