### ISSUE TITLE
New Feature : Change Conda Store's URL 

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#146]
Gator, when using Conda/Mamba as a backend, uses the binary available on the system on which it runs.

Using Conda Store as a backend, we need to give its URL. By default, and during our development cycles, this URL is hardcoded and considered being `localhost:5000`, but Conda Store may be deployed on another server, and another port than 5000.

Thus, we need to be able to edit this URL. I have listed two options, but other suggestions and ideas may come up :

- For the JupyterLab extension itself, we'll need a place in the UI to setup the API endpoint of Conda Store.
- For the standalone version (which actually spins a JupyterLab with the extension), we may pass the URL as an option in the command line.

This change will be necessary for the first phase of the project, as we don't intend on shipping code with an hardcoded URL.

You can see the original conversation [here](https://github.com/Quansight/gator/pull/21/commits/d7c24008f8018dc8ec93ea74cc679d01778c17ba#r707051347).

Next phases : 
- [ ] Define other options
- [ ] Scope the necessary work for the ones we'll make
- [ ] Implement

**Comment by pierrotsmnrd** [comment]
Work in progress in the [Quansight/gator::set-conda-store-url](https://github.com/Quansight/gator/tree/set-conda-store-url) branch.

**Comment by pierrotsmnrd** [comment]
- Internal review has been done
- merged, but into master
- Once we have merged into `mamba-org`'s repository, we will cherry pick the specific commit and open a PR on the dedicated branch upstream `conda-store-integration`

**Comment by peytondmurray** [comment]
Merged: https://github.com/mamba-org/gator/pull/161
