### ISSUE TITLE
[Meta] new UI for Gator

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#147]
This issue will hold all high-level / general purpose discussions for the new UI for Gator.

The main designer is @isabela-pf

**Comment by isabela-pf** [comment]
A round of mockups and a little prototype has been posted on [mamba-org/gator #157](https://github.com/mamba-org/gator/issues/157)!

**Comment by isabela-pf** [comment]
I don't have the permissions to assign this to myself, but you can assign it to me if it helps with the project management.

**Comment by costrouc** [comment]
Closing since we are now developing https://github.com/quansight/conda-store-ui
