### ISSUE TITLE
Pull request template on Quansight/gator

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#173]
As requested by @peytondmurray, we need a pull request template for the [UI repository Quansight/gator](https://github.com/Quansight/gator).

This template will eventually be merged to [mamba-org/gator](https://github.com/mamba-org/gator) so the template may need to be reworked down the road - that's something we'll overview with the mamba-org team.

**Comment by pierrotsmnrd** [comment]
Suggested sections by Peyton :

```md
## Summary
<!-- A 1 sentence summary of the change -->
## Changes
<!-- List of changes -->
## Related Issues
<!-- Links to related issues, if any -->
## Manual Testing
<!-- Information about how to test the PR manually -->
```

**Comment by pierrotsmnrd** [comment]
Some inspiration I used for our template : 

https://github.com/stevemao/github-issue-templates

https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/

**Comment by costrouc** [comment]
I don't have any strong feelings towards the templates though I do find them helpful. At a minimum I like to have a linked issue to the PR and the way it has been tested and how the reviewer could test it. I'd prefer to start small with this and grow it as we have needs.

**Comment by pierrotsmnrd** [comment]
@costrouc the discussion was mainly about the PR template for the Gator repository. 
If you're interested in having a PR template for the conda-store repo, we can either rename this issue to broaden its scope, or just close it and open another one :) as you prefer.
