### ISSUE TITLE
Rename the settings entry from « Conda » to « Gator »

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#175]
Gator has been originally developed to work with conda/mamba.
Thus, the name of the extension in the settings registry appears as "Conda" : 

![image](https://user-images.githubusercontent.com/756464/135267963-5d337453-ae21-4627-9409-79bf288e607e.png)

Once we're close to have our PR to Gator merged, we'll coordinate with the mamba-org team and suggest to rename this entry from "Conda" to "Gator".

**Comment by kcpevey** [comment]
Closing as this is no longer valid.
