### ISSUE TITLE
Make psycopg2 an optional dependency of conda-store-server

### ISSUE THREAD

**Issue by yuvipanda** [Quansight/conda-store#198]
sqlalchemy should theoretically just work with sqlite, so it would be nice to not have psycopg2 as a required dependency. The dependency is also on the [pscopg2](https://pypi.org/project/psycopg2/) package, rather than the [psycopg2-binary](https://pypi.org/project/psycopg2-binary) package - so conda-store-server installation fails if a compilation environment and `libpq-dev` are not available (see https://www.psycopg.org/articles/2018/02/08/psycopg-274-released/).

**Comment by pierrotsmnrd** [comment]
Hi @yuvipanda :) Thanks for your feedback.

Conda Store is designed to be database-agnostic. Sure, it can work with a simple sqlite backend, but it can also work with a postgres database for instance - as we can see in the [example docker files](https://github.com/Quansight/conda-store/tree/main/examples/docker).
So in the end, I think `psycopg2` remains necessary - getting rid of it would _force_ users to use sqlite and only this.

On the other hand, you're right about the use `psycopg2` vs `psycopg2-binary` and I [opened a PR](https://github.com/Quansight/conda-store/pull/205) for this.

**Comment by costrouc** [comment]
Hey @yuvipanda this makes sense. Yeup no reason that sqlalchemy has to run with postgres. I've removed this in PR #206

**Comment by pierrotsmnrd** [comment]
Haha, guess what : I mixed up `psycopg2` and `sqlalchemy`in my previous comment, which doesn't make any sense because of this 😅 as conda store is indeed database-agnostic, it's `sqlalchemy` that is necessary and `psycopg2` is obviously optional. 
Anyway, thank you all !
