### ISSUE TITLE
redirect_uri is not configurable when using JupyterHub Auth

### ISSUE THREAD

**Issue by yuvipanda** [Quansight/conda-store#199]
I'm trying to use conda-store-server as a JupyterHub managed service - so JupyterHub starts the process and supervises it. This vastly simplifies management in cases where this is possible - in my case, in TLJH.

However, the OAuth redirect_uri is not configurable in conda-store, and hence I get this error when trying to login to conda-store:

```
400 : Bad Request
Mismatching redirect URI.
```

The URL provided is `http://localhost:12000/hub/api/oauth2/authorize?client_id=service-conda-store&redirect_uri=http://localhost:12000/services/conda-store/oauth_callback/&response_type=code&scope=profile&state=<state>` - see the `redirect_uri` is fully qualified, and constructed with flask's [url_for](https://flask.palletsprojects.com/en/2.0.x/api/#flask.url_for). However, in the JupyterHub sqlite db, we see that the actual callback URL is `/services/conda-store/oauth_callback`, and defined relatively - as the hub is proxying requests to the server.

The redirect_uri constructed by flask uses runtime information - particularly, the host name - to construct its URL. I can't specify that properly in jupyterhub config, as that's determined at start up and I want users to be able to port-forward / proxy as necessary. Using relative URLs solves this quite nicely.

**Comment by pierrotsmnrd** [comment]
Thanks for reporting @yuvipanda.
This is beyond my skills. I know @costrouc is busy with PackagingCon these days, but he'll handle this.

**Comment by costrouc** [comment]
@yuvipanda as an update this was fixed in release 0.3.7. I added an `oauth_callback_url` trait to the generic oauth implementation. I currently have conda-store running on (mysql and postgresql), (bare metal systemd, kubernetes), and (jupyterhub and keycloak authentication). Let me know if the 0.3.7 did not fix this for you!
