### ISSUE TITLE
Consider using HubOAuth from jupyterhub package to implement jupyterhub auth

### ISSUE THREAD

**Issue by yuvipanda** [Quansight/conda-store#200]
https://github.com/jupyterhub/jupyterhub/blob/main/examples/service-whoami-flask/whoami-flask.py is the example for implementing a JupyterHub service with auth from flask. In particular, it uses the [HubOAuth](https://github.com/jupyterhub/jupyterhub/blob/e525ec7b5bfb6a943b720cdc4dd10a7b2205a2e4/jupyterhub/services/auth.py#L558) class from JupyterHub, making sure a number of things are set up properly for use with JupyterHub.

There's also [a fastapi example](https://github.com/jupyterhub/jupyterhub/tree/main/examples/service-fastapi).

https://github.com/Quansight/conda-store/issues/199 is what triggered me opening this. Code reuse is <3

**Comment by yuvipanda** [comment]
URL handling for users (for redirects) vs internal API calls would definitely be simplified here. JupyterHub sets `JUPYTERHUB_API_URL` (`http://127.0.0.1:15001/hub/api`) as an env var that should be used for all internal calls, and sets `JUPYTERHUB_SERVICE_PREFIX` (`/services/conda-store/`) for anything user facing.

**Comment by costrouc** [comment]
Thanks @yuvipanda for the links and examples for how to do this. Yeah totally agree this would be valuable to add and certainly prefer code reuse!

**Comment by dharhas** [comment]
Do we need to do this anyway to get things working on QHub?

**Comment by kcpevey** [comment]
@costrouc can you post a status update on this issue and close if no longer relevant?
