### ISSUE TITLE
Add API endpoint for exporting environment specifications as yaml

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/conda-store#203]
Currently the Flask server can export environments as YAML files by making a GET request to `/build/<build_id>/yaml/`. It would be useful to have this capability as part of the conda-store server API, in particular for exporting environments as part of conda-store support in [gator](https://github.com/mamba-org/gator).

I propose adding an endpoint at `/api/v1/build/<build_id>/yaml/`. If this is amenable to everyone, I'll make a pull request for this.

**Comment by costrouc** [comment]
Closing since #204 was merged.
