### ISSUE TITLE
API change : add a parameter to filter out dependencies packages 

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#241]
To achieve an usable alpha version of Gator UI, we need to distinguish "listed packages" (the ones from the env yml file) from the dependencies it has. For instance, if asking for `pandas`, `pandas` is the list package and `numpy` would be the dependency.

Let's add a parameter in the API request to filter out the dependency packages

Issue related to #242

**Comment by pierrotsmnrd** [comment]
Alternatively to changing the API, we can achieve the same goal ( have the list of listed packages without the dependencies ) in a two-step way : 

Starting from a given environment : 
- retrieve its `current_build_id` : `/api/v1/environment/[namespace]/[env_name]/` 
this yields a result similar to : 
```json
{
  "data": {
    "current_build_id": 2, 
    "id": 1, 
    "name": "env_test_1", 
    "namespace": {
      "id": 1, 
      "name": "default"
    }
  }, 
  "status": "ok"
}
```
- from this, retrieve its listed packages : `/api/v1/build/[current_build_id]/` which yields something like : 
```json

{
  "data": {
    "ended_on": "Wed, 16 Feb 2022 06:32:53 GMT", 
    "environment_id": 1, 
    "id": 2, 
    "scheduled_on": "Wed, 16 Feb 2022 06:31:56 GMT", 
    "size": 368554461, 
    "specification": {
      "created_on": "Wed, 16 Feb 2022 06:31:56 GMT", 
      "id": 2, 
      "name": "env_test_1", 
      "sha256": "b55c5f8389ce9b6e2b5a9b38ad742d739e6e76f06b24ff3b797bc72a41b1a01d", 
      "spec": {
        "channels": [
          "conda-forge"
        ], 
        "dependencies": [
          "ipykernel", 
          "pandas", 
        ], 
        "name": "env_test_1", 
        "prefix": null
      }
    }, 
    "started_on": "Wed, 16 Feb 2022 06:31:59 GMT", 
    "status": "COMPLETED"
  }, 
  "status": "ok"
}
```

The result under `["data"]["specification"]["spec"]["dependencies"]` is what's needed.

**Comment by kcpevey** [comment]
Closing as this is no longer valid
