### ISSUE TITLE
List of packages : don't show the dependencies

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#242]
Once #241 is done, the API will offer a parameter to distinguish between listed packages and dependencies.
Then, in the Gator UI : let's hide the dependencies.

**Comment by pierrotsmnrd** [comment]
An already-available solution that doesn't require modifying the API is presented here : https://github.com/Quansight/conda-store/issues/241#issuecomment-1041174794

**Comment by kcpevey** [comment]
Closing as this is no longer valid
