### ISSUE TITLE
Once user has successfully logged in they should be redirected to home page instead of user page

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#287]

**Comment by Palaksharma23** [comment]
I would like to work on this issue @costrouc

**Comment by costrouc** [comment]
@Palaksharma23 that would be greatly appreciated! 

There a few places that need to be changed:
 - https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/server/auth.py#L291
 - https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/server/auth.py#L228

The url_for needs to be changed to `ui_list_environments` and this will direct the user after login to the "home" page. Hope this helps with the issue and appreciate help!
