### ISSUE TITLE
Default docker images and docker-compose.yaml should not run as root

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#305]
Currently the conda-store-server and conda-store-worker containers within `docker-compose.yaml` and `examples/docker/docker-compose.yaml` along with the Dockerfiles within `conda-store` and `conda-store-server` all run as root by default. Running as root is not needed by conda-store and all images should be updated to reflect this. Probably running as some standard uid/gid such as `1000:100`.

**Comment by alanbraz** [comment]
I wanna try to help here
