### ISSUE TITLE
Builds should be in reverse chronological order.  

### ISSUE THREAD

**Issue by dharhas** [Quansight/conda-store#308]
Current ordering is alphabetical (I think) and looks odd. 

We should switch to reverse cronological / descending order so the most recent build is at the top.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/561301/169434964-85caa007-c8d7-4756-a3fc-83ec997dcc6b.png">

**Comment by anirrudh** [comment]
I've fixed this in a branch alongside some other improvements I'm working on. I'll link the PR when I raise it.

**Comment by kcpevey** [comment]
This is implemented in the conda-store-ui
