### ISSUE TITLE
[Discussion] Build number of an environment : what's the best ? 

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#311]
So far, the build numbers of environments are actually the build `id`.
So, the first build of an env can be numbered `13` and the second one `21` which is very confusing.

Consecutive builds should have consecutive build numbers. What is the best way to represent these build numbers, from a UI perspective ? 

Some ideas : 

- simply number them starting from 1, and represent them prefixed with "version" : `version 1`, `version 2`, ...

- Using a notation `X.Y` would imply multiple things : 
  - The first version number could be `0.1` 
  - At each new build, we suggest a new version number with an incremented minor version number `Y`
  - Then, either we let the user define the build number, to allow the increment of the major version number `X`. 
  - Or, we don't let the user define the build number, each new build increment the minor version number `Y`, but the user has a checkbox "new major version" that sets a version number at ' `(X+1).0`

**Comment by kcpevey** [comment]
I think the notation `X.Y` complicates things beyond what we're ready for at this point. 

I'd like to add date-based to the list of ideas.

**Comment by pierrotsmnrd** [comment]
Ideas from the meeting Monday May 30th 2022 : 
- Date of built is very relevant to represent consecutiveness, as well as indicate when the built was done
- Short github-like hash can be used to identify the builds (`a1b2c3`, `f9e8d7`...)
- Displaying them together makes sense to convey both informations (consecutiveness and identifying a build)

**Comment by dharhas** [comment]
I say we flip the order present the date as the primary identifier but it would have the shortened build hash in parenthesis.
