### ISSUE TITLE
Add Redis as a property of the conda_store object in app.py

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#312]
Redis has been added as part of my work on performances in this PR : https://github.com/Quansight/conda-store/pull/300/

It's used to keep track of locks on Celery tasks.
For the moment it's instantiating a Redis object when necessary.

Once my PR is done, let's move it in the conda_store object to make it available like the db object for example.

**Comment by pierrotsmnrd** [comment]
@costrouc  I think this is done now, isn't it ?

**Comment by costrouc** [comment]
@pierrotsmnrd yes this is done. Closing
