### ISSUE TITLE
Conda-store can't install packages from github

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/conda-store#317]
See: https://github.com/Quansight/qhub/issues/1305#issuecomment-1145347102

conda-store can't build packages listed in the environment.yml thusly:
``` 
- hvplot
- pip
- pip:
  - git+https://github.com/zarr-developers/numcodecs
  - git+https://github.com/observingClouds/xbitinfo
 ```
According to @viniciusdc :
> The env build is falling because conda-store has an [inbuilt validator](https://github.com/Quansight/conda-store/blob/11f8538a0f86c24f55e02bdc41de0fdf18639ce6/conda-store-server/conda_store_server/schema.py#L142) to inspect the pip/conda dependencies. And based on the [Requirement.parse()](https://setuptools.pypa.io/en/latest/pkg_resources.html#requirements-parsing) specifications, the "git+https://github.com/zarr-developers/numcodecs" string does not satisfies the PEP508 specifiers.

**Comment by peytondmurray** [comment]
@viniciusdc I'd be happy to take up this issue. I looked into how `pip` does this, and they just end up parsing a package as a VCS link if it has a `:` in the name. I think we can do the same here.

As far as I can tell they don't reuse much machinery from other projects (including setuptools) to handle any of this, and the bit that _does_ do this kind of requirement parsing is inside `pip._internal` which probably means we shouldn't reuse it and count on it remaining a stable feature forever.

**Comment by peytondmurray** [comment]
Under the hood conda-store makes use of [packaging](https://github.com/pypa/packaging) to parse pip dependencies. Packaging implements [PEP440](https://peps.python.org/pep-0440/), which means [VCS support](https://peps.python.org/pep-0440/#direct-references) is slightly different from `pip`. To do this, You'll need to do something like this in your `environment.yml`:

```
name: test-env
dependencies:
- hvplot
- pip
- pip:
  - numcodecs @ git+https://github.com/zarr-developers/numcodecs@434c7b14ea7e8c758e5a65dbc903270040b0c0e7
  - xbitinfo @ git+https://github.com/observingClouds/xbitinfo@285446fb7c39eb5e5f1c1a8b07a0831046ada000
```

Here, the dependencies follow

```
- <package name> @ git+<web address of git repository>@<commit hash to retrieve>
```

In the example above, I've put in the commit hashes to retrieve by hand from the latest commits on those repositories. @rsignell-usgs Could you give this a try?

One thing we should definitely add is to improve exception handling and add some documentation around this to help avoid confusion.

**Comment by peytondmurray** [comment]
Closing this in favor of https://github.com/Quansight/conda-store/issues/325.
