### ISSUE TITLE
Docker example: bad redirect after authenticating with JupyterLab

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/conda-store#319]
To reproduce:
1. `cd examples/docker && docker compose up --build`
2. Navigate to `localhost:5000` to access the conda-store frontend
3. Click "Login", then "Sign in with JupyterHub"
4. Sign in with `admin`/`test`. You'll be redirected to JupyterLab
5. Navigate back to `localhost:5000`
6. Click "Login" again, then "Sign in with JupyterHub"

At this point an error page will appear: 

![image](https://user-images.githubusercontent.com/14017872/172717115-e9310d5b-9911-4de7-93a0-d0d5f741f5de.png)

with the URL being set to

`https://conda-store.localhost/hub/api/oauth2/authorize?client_id=service-this-is-a-jupyterhub-client&redirect_uri=http://localhost:5000/conda-store/oauth_callback/&response_type=code&scope=profile&state=qPOBzY1ixgLwFqBbLXTTtD-Agqj63tnyHRzGyWlEmHA`

**Comment by costrouc** [comment]
Closing since now resolved.
