### ISSUE TITLE
Allow new channels to be added dynamically

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#343]
Currently channels are restricted to only those listed in https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/app.py#L100-L107 and this is by design so that we can restrict users to only a subset of channels. However at time it is necessary just freely accept all channels.

I propose that `c.CondaStore.default_allow_channels` be created as a boolean trait. If true any new environment encountered in https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/app.py#L26-L31 and https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/build.py#L43-L48 should be instead added to the database via a sqlalchemy transaction.

Channels can be added via:
 - normalize the channel name https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/conda.py#L23-L28
 - and added via the orm CondaChannel class https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/orm.py#L280-L282

**Comment by costrouc** [comment]
This issue will close https://github.com/Quansight/conda-store/issues/299.

**Comment by csadorf** [comment]
I'm interested in contributing to this issue.

**Comment by costrouc** [comment]
Resolved by #358
