### ISSUE TITLE
`Submit` button is unresponsive

### ISSUE THREAD

**Issue by iameskild** [Quansight/conda-store#382]
When I try to create a new env, I am unable to because the `Submit` button doesn't seem to be responsive. This is the same for the `Token` button. I am logged in and I have attempted this on two different Nebari deployments. I have attached console logs.

Known affected versions: `v0.4.9` and `v0.4.11` (presumably `v0.4.10` as well)

[livedemo.qhub.dev-1660781750506.log](https://github.com/Quansight/conda-store/files/9366737/livedemo.qhub.dev-1660781750506.log)

**Comment by pierrotsmnrd** [comment]
Hi @iameskild  :)

Can you share the YAML of the env you were trying to build ? 
The current UI has this behavior, that when the YAML doesn't validate, the build isn't triggered but no feedback is shown to the user. We're working on it.

**Comment by viniciusdc** [comment]
MIssing `c.CondaStoreServer.behind_proxy = True` in the Qhub server configutation. See [ref.](https://github.com/Quansight/conda-store/blob/5a2bebf5d96532993cf2ff25499dd74ce114155a/conda-store-server/conda_store_server/server/app.py#L88)

```
conda-store:
   extra-settings:
       CondaStoreServer:
          behind_proxy: true
```

**Comment by iameskild** [comment]
Apologies this issue should have been opened on the QHub side. As @viniciusdc mentioned, the resolution was to add `c.CondaStoreServer.behind_proxy = True` to the `conda_store_config.py`.
