### ISSUE TITLE
Update landing page GIF

### ISSUE THREAD

**Issue by pavithraes** [Quansight/conda-store#405]
In #402, we added a GIF to show a preview of the UI.

We need to update it:
- [ ] The end slide call-to-action is to visit `conda.store`, we can say something else here because we're already on `conda.store`.
- [ ] TBD

**Comment by costrouc** [comment]
@pavithraes I worked to compress the image from .gif to .webp which reduced the size to around 25MB uncompressed. Does this issue still need to be open?

**Comment by trallard** [comment]
@pavithraes  following on the last comment, is this still applicable or can be closed?

**Comment by pavithraes** [comment]
Thanks for following up! Yes, this can be closed. :)
