### ISSUE TITLE
Generated Lockfile Wrong Package md5

### ISSUE THREAD

**Issue by ranchodeluxe** [Quansight/conda-store#431]
`server/worker image`:  custom image built off `main`
`conda-lock version`: 1.4.0

Came to this issue from #430. It seems the lockfile generated from the simple spec (see below) is not pointing to the `tar.bz2` md5 but the `.conda` md5:

When I try to build an environment with `conda-lock` using the lockfile def (see below) I get the following:

```
INFO:root:nspr-4.33
ERROR:root:Conda detected a mismatch between the expected content and downloaded content
ERROR:root:for url 'https://repo.anaconda.com/pkgs/main/linux-64/nspr-4.33-h295c915_0.tar.bz2'.
ERROR:root:  download saved to: /opt/conda/pkgs/nspr-4.33-h295c915_0.tar.bz2
ERROR:root:  expected md5: 78454e8819eb6701abc74b2ab2889f21
ERROR:root:  actual md5: 28808460055d2c42c58edd8639ce530c
ERROR:root:
ERROR:root:
ERROR:root:
ERROR:root:ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
ERROR:root:for url 'https://repo.anaconda.com/pkgs/main/linux-64/nspr-4.33-h295c915_0.tar.bz2'.
ERROR:root:  download saved to: /opt/conda/pkgs/nspr-4.33-h295c915_0.tar.bz2
ERROR:root:  expected md5: 78454e8819eb6701abc74b2ab2889f21
ERROR:root:  actual md5: 28808460055d2c42c58edd8639ce530c
```

Notice that the md5 is correct but not for the `tar.bz2`, it's for the `.conda` package:

<img width="1656" alt="Screen Shot 2023-02-07 at 6 01 01 AM" src="https://user-images.githubusercontent.com/208859/217268122-38a23a39-b24f-4035-89f7-17d2f5a3cead.png">

You can browse the packages here to see for yourself:

https://repo.anaconda.com/pkgs/main/linux-64/

**Pinned YAML** used in build:
```
name: scratch
channels:
- conda-forge
dependencies:
- nspr=4.33=h295c915_0
```

**Lockfile Generated** from build:
```
#platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-12.2.0-h65d4601_19.tar.bz2#e4c94f80aef025c17ab0828cd85ef535
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-12.2.0-h46fd767_19.tar.bz2#1030b1f38c129f2634eae026f704fe60
https://repo.anaconda.com/pkgs/main/linux-64/nspr-4.33-h295c915_0.tar.bz2#78454e8819eb6701abc74b2ab2889f21
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2#d7c89558ba9fa0495403155b64376d81
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2#73aaf86a425cc6e73fcf236a5a46396d
https://conda.anaconda.org/conda-forge/linux-64/libgomp-12.2.0-h65d4601_19.tar.bz2#cedcee7c064c01c403f962c9e8d3c373
```

**Comment by dharhas** [comment]
@costrouc can you look at this

**Comment by costrouc** [comment]
@ranchodeluxe does conda-lock not support `.conda` files? What is the version of conda-lock that you are using. The `.conda` package format is starting to become the standard on conda-forge and soon defaults as well.
