### ISSUE TITLE
Okay to use `mamba clean --all` on conda-store pod?

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/conda-store#434]
Is it okay to shell into the conda-store pod and do: `mamba clean --all --yes`?

When I try to make modifications to my conda-store environments I'm getting:
``` 
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
python: /home/conda/feedstock_root/build_artifacts/libsolv_1649959712616/work/src/rules.c:261: solver_addrule: Assertion `!p2 && d > 0' failed.
```
and I'm thinking that blowing away the cache might fix things?

**Comment by viniciusdc** [comment]
Hi @rsignell-usgs, thanks for bringing in this, @costrouc I don't think this would harm the conda-store service, but could you let us know if there is another way around this (cleaning cache) or if the outlined approach is enough?

**Comment by viniciusdc** [comment]
@rsignell-usgs  could you share the environment dependencies that you attempted to build?

**Comment by rsignell-usgs** [comment]
Yep!  Here's the env:  https://gist.github.com/rsignell-usgs/0b76caba57ed5c43783cd1cb15c808d2

**Comment by rsignell-usgs** [comment]
I'm having this issue again when building `conda-store` environments.    An environment that normally builds successfully in 12 minutes failed to build after 45 minutes, and the only line in the "full logs" is:
``` 
python: /home/conda/feedstock_root/build_artifacts/libsolv_1649959712616/work/src/rules.c:261: solver_addrule: Assertion `!p2 && d > 0' failed.
```
@iameskild or @viniciusdc I think one of you figured out what to do last time, but I can't remember, so hopefully asking it here we can record the fix for the future!

**Comment by dharhas** [comment]
@costrouc @iameskild since this is something that was working and now isn't, wouldn't it mean that either:

- there is a cache issue
- the conda-store storage is full
- conda-store or nebari version upgrade changed things

@rsignell-usgs can you 
1. make any completely new environment?
2. make a new environment with these packages.

**Comment by dharhas** [comment]
fyi. That particular environment (from the gist) is stuck on building (24 hrs later) when I try it on demo.nebari.dev as well.

**Comment by rsignell-usgs** [comment]
Okay, I tried the environment locally and there are conflicts that were preventing mamba from building. 
I removed the troublesome packages and now it builds.    
So:
* it appears that my `mamba clean --all` cleaned up the cache issue.
* it would be very helpful to see the logs for envs as they are actively building

**Comment by rsignell-usgs** [comment]
Update: still says "building", now two hours later.   Not sure what to do.

**Comment by rsignell-usgs** [comment]
Okay, turns out this is a GUI/sync issue -- the environment actually completed.    When I tried building another environment (151), suddenly 150 said completed.

**Comment by rsignell-usgs** [comment]
Also, it was recommended to delete old environments using the gui, and while on the gui side it appears to work (we get the greyed out env), I still see the environments when I log into the conda-store pod.  So keep using the "shell into the pod using k9s and delete old environments with `rm -rf`" method?

**Comment by costrouc** [comment]
Closing this since this is related to conda-store managing storage space. There is now a way for conda-store to protect from running out of space.
