### ISSUE TITLE
Integrate conda-store-ui into conda-store-server

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#438]
- [ ] conda-store-ui is bundled as static files within each npm release
 - [ ] debating on how to include the assets:
       - in the pyproject/setup.cfg build download/include the static assets (ideally)
       - in the dockerfile build
  - [ ] serve these static assets under a new endpoint `/ui`

**Comment by dharhas** [comment]
How about making the conda-store-ui available at `/` and moving the fastapi ui to `/admin`. Also, I guess for Nebari we will also have the JLab installed version.
