### ISSUE TITLE
Conda-Store trait for indexed channels

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#439]
Currently the indexed conda channels are the same as the allowed channels. We should separate this logic so that we can control which channels have autocomplete even when we explicitly allow all channels.

These are the channels for which we know the packages that are available. This will fetch/prepopulate the available packages. I am completely open to a better trait name.

**Comment by pierrotsmnrd** [comment]
@costrouc can you give a reproduction scenario please ?

**Comment by costrouc** [comment]
@pierrotsmnrd not sure entirely what you mean. Are you asking for a scenario where in the past things would not have worked?

**Comment by pierrotsmnrd** [comment]
Yes, so I can understand better what's going on

**Comment by costrouc** [comment]
So current there is only one setting

```python
c.CondaStore.allowed_conda_channels = ['conda-forge']
```

This has loaded behavior. It:
  - sets `conda-forge` as the only allowed channel
  - conda-store will search/index only this particular channel in it's package database tables.
  - if `allowed_conda_channels` is the empty list e.g. `[]` then all channels are allowed in conda-store ... but they conda-store doesn't know which channels to index

I'm proposing removing the "implicit" behavior of `allowed_conda_channels` where it is used for getting the channels to index and split into a `indexed_conda_channels` trait which is used.

So 

```python
c.CondaStore.allowed_conda_channels = []
c.CondaStore.indexed_conda_channels = ['conda-forge', 'defaults']
```

Would allow conda-store to "know" these are the particular channels that I should index and have available for searching. As you can tell with previous behavior `c.CondaStore.allowed_conda_channels = []` would have made it so that conda-store doesn't know which channels to index.
