### ISSUE TITLE
Allow inclusion of private packages

### ISSUE THREAD

**Issue by kcpevey** [Quansight/conda-store#495]
Its very common to need private packages in environments. For open git repos, we can add them as pip packages inside the environment.yml. We need a way to do this for private packages. 

Note: the only available workaround is to manually download the repo and pip install into your local environment space, but this will not be available to others.

**Comment by dharhas** [comment]
You can do this for private repo's via pip + git if you don't mind the token being stored in plaintext with is a security hole - https://docs.readthedocs.io/en/stable/guides/private-python-packages.html

Outside of that if you already have an internal mirror to host private packages then this will also work.

**Comment by costrouc** [comment]
Closing this since I've tested and added docs in https://github.com/Quansight/conda-store/pull/504. Turns out that this works out of the box already in older conda-store versions.
