### ISSUE TITLE
Add finer information on state of conda-store environment builds

### ISSUE THREAD

**Issue by kcpevey** [Quansight/conda-store#56]
I've had several env build failures recently (various reasons) that weren't caught by ci testing. On multiple occasions we've had to go into `kubectl`/`k9s` to see the failure or were it got hung up. 

I like how everything is automated here, but when my gh action for deployment is showing "green" its misleading that the deployment is complete. I'd like some tooling (or documentation) to tell me how to set up `kubectl` to see what's going on after gh actions has done it's thing. 

I know the pretense is that qhub is k8s for people who don't know k8s, but I need some additional monitoring capability.

**Comment by costrouc** [comment]
I do not think that realtime logs will be possible. However I do think it would be easy to add further information with a progress bar for each environment.
  - solve
  - build
  - create lockfile
  - create conda pack
  - create conda docker image
And this should be reflected in a progress bar.

**Comment by kcpevey** [comment]
This is complete to my liking so I'm going to close.
