### ISSUE TITLE
Deploy Rstudio via conda-store?

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/conda-store#57]
@costrouc , Could conda-store be a solution to the issue below, providing a way for JupyterHub users to use Rstudio?
https://github.com/pangeo-data/pangeo-docker-images/issues/163#issuecomment-730498775

**Comment by leej3** [comment]
Also check out rocker if you are thinking of putting rstudio in a container. They’ve implemented it very nicely.

**Comment by costrouc** [comment]
@rsignell-usgs conda-store could absolutely be used for packaging rstudio environments. I don't know much about R and conda packaging. I'm closing this issue but it would be nice to have a demo conda store environment that creates an R environment with RStudio inside.
