### ISSUE TITLE
Tests are out of date

### ISSUE THREAD

**Issue by jaimergp** [Quansight/conda-store#68]
It looks like the `tests/` folder is out of date. It tries to import `conda_store` instead of `conda_store_server`, and most are failing.

**Comment by pierrotsmnrd** [comment]
One major part that needs to be tested is the API.

@costrouc What's the best solution to test it ? in terms of lib, architecture, integration with github actions ...

**Comment by pierrotsmnrd** [comment]
After discussing with @costrouc :

####  Regarding Integration Tests : 
- The current tests suite is a cypress test, that tests the UI. It even generates a video of the result. (see the artifcats at the bottom [of this page](https://github.com/Quansight/conda-store/actions/runs/1239080049))
- We could add a pytest after this test. 

The only problem is that it's heavy to run this on our machines.
One alternative solution is to have the test suite with a similar environment than the example docker-compose ( at least conda-store-server + postgres + 1 worker), and the worker would be tweak to fake the build of the environments (which is the longest and most resource-consuming step).

#### Regarding Unit tests : 
We mainly discussed testing the API - which is our topic these days.
One scenario is : let's make a SQLAlchemy script that mimics the creation of namespaces, environments, builds etc.
Use this to dump the Postgres DB and use it in our docker containers for the tests.
Updating the model will imply modifying this script and the SQL dump. That can seem boring but it's like modifying any other unit test when updating code.


#### Actions : 
I'll explore this latest track for the API as this is the most needed at the moment.

**Comment by costrouc** [comment]
Resolved since tests are now current.
