### ISSUE TITLE
Conda-store garbage collection

### ISSUE THREAD

**Issue by prasunanand** [Quansight/conda-store#7]
https://github.com/Quansight/quansight-internal-support/issues/46

Can you modify README so I can hack on conda-store ?

**Comment by costrouc** [comment]
Remove the symlinks in `/home/conda/environments`. I will in the near future be implementing a garbage collect feature similar to docker to remove no longer used environments.

```
costrouchov@quansight.com@jupyter-costrouchov-40quansight-2ecom:/home/conda/environments$ ls -la
total 24
drwxr-xr-x 2 0 0 4096 Sep  3 21:28 .
drwxr-xr-x 5 0 0 4096 Sep  3 17:12 ..
lrwxrwxrwx 1 0 0   88 Sep  3 21:22 cudev -> /home/conda/store/be4703f80324bd11148efc58fc6d12cec4e76db0e9e2ab627e9870017363d34e-cudev
lrwxrwxrwx 1 0 0   90 Sep  3 21:28 default -> /home/conda/store/2a5c4f7f7f9a84791943c9430f0b8894d23ad54100e7e236af73bd4f2bdd5e1b-default
lrwxrwxrwx 1 0 0   93 Sep  3 19:22 sixtynorth -> /home/conda/store/fdb9413f700026cec99a17e8232f9ebfbba855c1cecc7cd1b885666fd07fcaa1-sixtynorth
lrwxrwxrwx 1 0 0   91 Sep  3 21:25 training -> /home/conda/store/f82453760e5e8d25c668eb43cb7bfc98a8170b9b8562369aaab4dbaca10e0122-training
```

**Comment by costrouc** [comment]
Needs support for two types of collection:
 - old builds (say older than x days)
 - n oldest builds to be remove (keep m latest builds for each environment)

**Comment by costrouc** [comment]
Depends on https://github.com/Quansight/conda-store/issues/22

**Comment by costrouc** [comment]
Partially implemented in https://github.com/Quansight/conda-store/pull/94. Now need a cron job to check for unused builds and what that build condition might be.

**Comment by kcpevey** [comment]
@costrouc is this still valid?
