### ISSUE TITLE
conda-store not working on macOS

### ISSUE THREAD

**Issue by anirrudh** [Quansight/conda-store#9]
conda-store is not working on macOS and needs a simple fix. This is just an issue to track progress; should be done shortly!

**Comment by costrouc** [comment]
@anirrudh is this still an issue?

**Comment by anirrudh** [comment]
Nope! Closing :) This was only a thing a really long time ago, and properly mounting the folders/creating them beforehand works. When the time comes, we can always write something that might be macOS compatible if needed. Closing.
